version: '2'
services:
    pricingplatformldapsvc-app:
        image: pricingplatformldapsvc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://pricingplatformldapsvc-mssql:1433;database=PricingPlatformLdapSvc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://pricingplatformldapsvc-elasticsearch:9200
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    pricingplatformldapsvc-mssql:
        extends:
            file: mssql.yml
            service: pricingplatformldapsvc-mssql
    pricingplatformldapsvc-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: pricingplatformldapsvc-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
